.idea/CMPUT301Project.iml
.idea/misc.xml
.idea/modules.xml
.idea/workspace.xml
android/301Project/app/src/main/java/com/example/a301project/Ingredient.java

Add Ingredient Class

---

android/301Project/.idea/misc.xml
android/301Project/app/src/main/AndroidManifest.xml
android/301Project/app/src/main/java/com/example/a301project/RecipeActivity.java
android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
android/301Project/app/src/main/res/layout/activity_recipe.xml
android/301Project/app/src/main/res/layout/recipe_row_layout.xml

* Add sorting feature to RecipeActivity
Resolves #14

Add Sorting to Recipe Activity

---

android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
android/301Project/app/src/main/res/layout/activity_ingredient.xml
android/301Project/app/src/main/res/layout/add_edit_ingredientlayout.xml
android/301Project/app/src/main/res/layout/ingredient_content.xml

- sort ingredients by entry, location, best before date, and category in alphabetical order or by most recent date
- sort can be selected as both ascending or descending order

Added ingredient sorter

---

android/301Project/.idea/androidTestResultsUserPreferences.xml
android/301Project/app/src/androidTest/java/com/example/a301project/IngredientActivityTest.java
android/301Project/app/src/main/res/layout/activity_ingredient.xml

Still a lot of intent testing to do but did a good chunk

Started IngredientActivity Intent testing

---

.gitignore
android/301Project/app/src/main/java/com/example/a301project/Ingredient.java
android/301Project/app/src/main/java/com/example/a301project/IngredientController.java

I don't know where the .gitignore went, so I added it back to exclude .DS_Store (Mac specific files) automatically from the repo. Also added some javadocs.

Added javadocs and .gitignore

---

android/301Project/app/src/main/java/com/example/a301project/RecipeListAdapter.java

Update Recipe PrepTime to Min

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/res/layout/add_edit_ingredientlayout.xml
android/301Project/app/src/main/res/values/strings.xml

- category spinner for ingredients include 'fruit', 'vegetable', 'protein', 'sweets', 'grain', 'seasoning', 'condiments'

Added Category spinner for ingredients

---

android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java

Fixed Firestore conversion bug for the shopping list

Fixed Firestore conversion bug for the shopping list

---

android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java

Refactor methods to use a new method that automatically casts the value for us.

Refactor Firebase Controller Getters

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/Recipe.java
android/301Project/app/src/main/java/com/example/a301project/RecipeActivity.java
android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
android/301Project/app/src/main/res/layout/activity_recipe.xml
android/301Project/app/src/main/res/layout/add_edit_ingredientlayout.xml
android/301Project/app/src/main/res/layout/add_edit_recipe_layout.xml

This PR adds the Add, Edit and Delete Recipe Functionality in the app.

Feat: Add, Edit, Delete Recipe functionality

---

android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/res/values/strings.xml

- breakfast, lunch, dinner, dessert, snack categories for recipe

added categories for recipe

---

android/301Project/.idea/misc.xml
android/301Project/app/build.gradle
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/RecipeListAdapter.java
android/301Project/app/src/main/res/drawable-hdpi/rounded_rect_trans.xml
android/301Project/app/src/main/res/layout/add_edit_recipe_layout.xml
android/301Project/app/src/main/res/layout/recipe_row_layout.xml

* Add ability to upload an image or camera photo to firebase

Add Upload & Camera

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/CustomList.java
android/301Project/app/src/main/java/com/example/a301project/IngredientActivity.java
android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
android/301Project/app/src/main/java/com/example/a301project/MealPlan.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanActivity.java
android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
android/301Project/app/src/main/java/com/example/a301project/Recipe.java
android/301Project/app/src/main/java/com/example/a301project/RecipeActivity.java
android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
android/301Project/app/src/main/java/com/example/a301project/RecipeListAdapter.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListActivity.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListAdapter.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java

- every class except for meal plans

loads of javadoc

---

android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanActivity.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanListAdapter.java

Add JavaDoc for MealPlanActivity and MealPlanListAdapter

---

android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java

https://user-images.githubusercontent.com/59630201/200049034-f7944031-a535-4537-8d24-dab9253521d9.mov

Fix Null Image Bug

---

android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java

Make the delay abit longer so the dropdown renders above not behind the keyboard

Update Ingredient Dropdown Delay

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/res/values/strings.xml

- user can add their own category, location, and units in addition to predetermined spinner options

user customizable all spinners in ingredient class

---

android/301Project/app/src/main/java/com/example/a301project/RecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/RecipeListAdapter.java

Fix ImageView Bug

---

android/301Project/app/build.gradle
android/301Project/app/src/main/AndroidManifest.xml
android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientController.java
android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeController.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
android/301Project/app/src/main/java/com/example/a301project/NavActivity.java
android/301Project/app/src/main/java/com/example/a301project/RecipeController.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
android/301Project/build.gradle
android/301Project/gradle/wrapper/gradle-wrapper.properties

* Added email and password login to the app
Resolves #98 
https://user-images.githubusercontent.com/59630201/202827386-8c2ec4c3-24f8-42a5-bcc1-c9a7f11ce8a1.mov

Add User Login Functionality

---

android/301Project/app/src/main/java/com/example/a301project/NavActivity.java

Add Google Login

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientController.java
android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java

Fixed Ingredient Category spinner, can't add duplicate, will select correct value on cancel or when duplicate is entered, will not close AlertDialog for empty value, user can't add empty value, and it automatically adds the default options from strings.xml
Still have to copy the functionality for Ingredient unit and location as well as recipe category. Also deal with new user ?

Fixed Ingredient Category spinner

---

android/301Project/app/src/main/java/com/example/a301project/NavActivity.java

Set the new DEBUG property to true when developing to have it auto login as the admin account.
Set it back to false before making PRS.

Auto Login as Admin with Flag

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientController.java
android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeController.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/NavActivity.java

Finished Ingredient + Recipe Spinners

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/IngredientController.java
android/301Project/app/src/main/java/com/example/a301project/IngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/RecipeController.java

Ingredient and Recipe Add/Edit fragments -> show error messages instead of closing
Fixed bug where a logged in user wasn't able to delete an ingredient or a recipe.

Fixed Add/Edit Fragments + User Deletion Bug

---

android/301Project/.idea/deploymentTargetDropDown.xml
android/301Project/app/src/main/java/com/example/a301project/AddEditMealPlanFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/MealPlan.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanController.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanFragment.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanListAdapter.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanRecipeListAdapter.java
android/301Project/app/src/main/java/com/example/a301project/Recipe.java
android/301Project/app/src/main/res/layout/activity_meal_plan.xml
android/301Project/app/src/main/res/layout/add_edit_mealplan_layout.xml
android/301Project/app/src/main/res/layout/add_edit_recipe_layout.xml
android/301Project/app/src/main/res/layout/meal_plan_layout.xml

Still need:
- display ingredient and recipe list under meal plan layout
- add filter restriction for end date must be after start date

Add MealPlan

---

android/301Project/app/src/main/java/com/example/a301project/AddEditMealPlanFragment.java
android/301Project/app/src/main/res/layout/add_edit_mealplan_layout.xml

- I commented out something by accident in the earlier push, all good now
- changed the layout of add meal fragment to fix display of the delete button

slight meal plan fixes

---

android/301Project/app/src/main/java/com/example/a301project/AddEditMealPlanFragment.java
android/301Project/app/src/main/java/com/example/a301project/MealPlanController.java

- same as ingredient and recipe, reject missing fields without exiting the fragment

Meal plan empty fields fragment fixed

---

android/301Project/app/src/main/java/com/example/a301project/MealPlanController.java
android/301Project/app/src/main/res/layout/add_edit_mealplan_layout.xml
android/301Project/app/src/main/res/layout/meal_plan_layout.xml

- can't enter ingredients and recipes that doesn't exist in storage
- can only select from existing
- meal plan deletion had a firebase issue, fixed now

fixed meal plan deletion bug and disabled customized inputs in meal plan

---

android/301Project/app/src/main/res/layout/activity_meal_plan.xml
android/301Project/app/src/main/res/layout/meal_plan_layout.xml

* Updated the padding on the top and the card view to render again

Fix Meal Plan UI

---

android/301Project/.idea/deploymentTargetDropDown.xml
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListFragment.java
android/301Project/app/src/test/java/com/example/a301project/ShoppingListControllerTest.java

add the ShopplinglistControllerTest
fixed the mock issue

Zyu6 unittest

---

android/301Project/app/src/main/java/com/example/a301project/AddEditIngredientFragment.java
android/301Project/app/src/main/java/com/example/a301project/AddEditRecipeFragment.java
android/301Project/app/src/main/java/com/example/a301project/Ingredient.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingItem.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListFragment.java
android/301Project/app/src/main/res/layout/activity_shopping_list.xml

** ShoppingItem is NO longer TypeOf Ingredient -> feedback from marking, 
- get recipes from Firebase in ShoppingList, 
- did some fixes to combine same name items in shopping list, 
- added a warning dialog if user tries to cancel purchasing an ingredient,
-  and added a shoppinglist empty message**

ShoppingList changes

---

android/301Project/app/src/main/java/com/example/a301project/ShoppingListAdapter.java
android/301Project/app/src/main/java/com/example/a301project/ShoppingListController.java
android/301Project/app/src/main/res/layout/shopping_row_layout.xml

Fixed a shopping list bug ->shows unit and category for applicable ShoppingItems
Used for loops

ShoppingList

---

android/301Project/app/src/main/java/com/example/a301project/AddEditMealPlanFragment.java
android/301Project/app/src/main/java/com/example/a301project/MealPlan.java

What is says in the title. Meal plan add/edit will be rejected if the start date is before the end date
resolves #112

Added filter to meal plan so that startDate <= endDate
